job:
  tags:
    - docker
# rcmdcheck:
  image: rocker/verse
  script:
    # create a unique env var for the cache.
    - export DATE=$(date '+%d-%m')

    # install dependencies
    - R -q -e 'install.packages("remotes")'
    - R -q -e 'if (getRversion() < "3.2" && !requireNamespace("curl")) install.packages("curl")'
    - R -q -e 'remotes::install_github("ropensci/tic", upgrade = "always"); print(tic::dsl_load()); tic::prepare_all_stages()'
    - R -q -e 'tic::before_install()'
    - R -q -e 'tic::install()'

    # check R package
    - R -q -e 'tic::before_script()'
    - R -q -e 'tic::script()'

    # run code coverage
    - R -q -e 'tic::after_success()'

cache:
  key: ${DATE}
  paths:
    - /usr/local/lib/R/site-library
