job:
  tags:
    - docker
# rcmdcheck:
  image: rocker/verse
  script:
    # create a unique env var for the cache.
    - export DATE=$(date '+%d-%m')

    # install dependencies
    - R -q -e 'options(repos = c(ropensci = "https://ropensci.r-universe.dev", getOption("repos"))); install.packages("tic")'
    - R -q -e 'tic::before_install()'
    - R -q -e 'tic::install()'

    # check R package
    - R -q -e 'tic::before_script()'
    - R -q -e 'tic::script()'

    # run code coverage
    - R -q -e 'tic::after_success()'

cache:
  key: ${DATE}
  paths:
    - /usr/local/lib/R/site-library
