// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ContrastRank
NumericVector ContrastRank(NumericMatrix Hetx, List PMat, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_ContrastRank(SEXP HetxSEXP, SEXP PMatSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< List >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(ContrastRank(Hetx, PMat, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// ContrastRankNested
NumericVector ContrastRankNested(NumericMatrix Hetx, NumericMatrix vMat_big, List PMat, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_ContrastRankNested(SEXP HetxSEXP, SEXP vMat_bigSEXP, SEXP PMatSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat_big(vMat_bigSEXP);
    Rcpp::traits::input_parameter< List >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(ContrastRankNested(Hetx, vMat_big, PMat, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// ContrastValue
NumericVector ContrastValue(NumericMatrix Hetx, List PMat, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_ContrastValue(SEXP HetxSEXP, SEXP PMatSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< List >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(ContrastValue(Hetx, PMat, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// ContrastValueNested
NumericVector ContrastValueNested(NumericMatrix Hetx, NumericMatrix vMat_big, List PMat, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_ContrastValueNested(SEXP HetxSEXP, SEXP vMat_bigSEXP, SEXP PMatSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat_big(vMat_bigSEXP);
    Rcpp::traits::input_parameter< List >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(ContrastValueNested(Hetx, vMat_big, PMat, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// DissimilarityRank
NumericVector DissimilarityRank(NumericMatrix Hetx, List PMat, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_DissimilarityRank(SEXP HetxSEXP, SEXP PMatSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< List >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(DissimilarityRank(Hetx, PMat, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// DissimilarityRankNested
NumericVector DissimilarityRankNested(NumericMatrix Hetx, NumericMatrix vMat_big, List PMat, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_DissimilarityRankNested(SEXP HetxSEXP, SEXP vMat_bigSEXP, SEXP PMatSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat_big(vMat_bigSEXP);
    Rcpp::traits::input_parameter< List >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(DissimilarityRankNested(Hetx, vMat_big, PMat, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// DissimilarityValue
NumericVector DissimilarityValue(NumericMatrix Hetx, List PMat, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_DissimilarityValue(SEXP HetxSEXP, SEXP PMatSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< List >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(DissimilarityValue(Hetx, PMat, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// DissimilarityValueNested
NumericVector DissimilarityValueNested(NumericMatrix Hetx, NumericMatrix vMat_big, List PMat, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_DissimilarityValueNested(SEXP HetxSEXP, SEXP vMat_bigSEXP, SEXP PMatSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat_big(vMat_bigSEXP);
    Rcpp::traits::input_parameter< List >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(DissimilarityValueNested(Hetx, vMat_big, PMat, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// Entropy
NumericVector Entropy(NumericMatrix Hetx, List PMat, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_Entropy(SEXP HetxSEXP, SEXP PMatSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< List >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(Entropy(Hetx, PMat, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// EntropyNested
NumericVector EntropyNested(NumericMatrix Hetx, NumericMatrix vMat_big, List PMat, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_EntropyNested(SEXP HetxSEXP, SEXP vMat_bigSEXP, SEXP PMatSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat_big(vMat_bigSEXP);
    Rcpp::traits::input_parameter< List >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(EntropyNested(Hetx, vMat_big, PMat, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// EntropyParallel
double EntropyParallel(NumericVector Hetx, NumericMatrix PMat, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_EntropyParallel(SEXP HetxSEXP, SEXP PMatSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(EntropyParallel(Hetx, PMat, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// HomogeneityRank
NumericVector HomogeneityRank(NumericMatrix Hetx, List PMat, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_HomogeneityRank(SEXP HetxSEXP, SEXP PMatSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< List >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(HomogeneityRank(Hetx, PMat, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// HomogeneityRankNested
NumericVector HomogeneityRankNested(NumericMatrix Hetx, NumericMatrix vMat_big, List PMat, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_HomogeneityRankNested(SEXP HetxSEXP, SEXP vMat_bigSEXP, SEXP PMatSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat_big(vMat_bigSEXP);
    Rcpp::traits::input_parameter< List >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(HomogeneityRankNested(Hetx, vMat_big, PMat, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// HomogeneityValue
NumericVector HomogeneityValue(NumericMatrix Hetx, List PMat, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_HomogeneityValue(SEXP HetxSEXP, SEXP PMatSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< List >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(HomogeneityValue(Hetx, PMat, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// HomogeneityValueNested
NumericVector HomogeneityValueNested(NumericMatrix Hetx, NumericMatrix vMat_big, List PMat, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_HomogeneityValueNested(SEXP HetxSEXP, SEXP vMat_bigSEXP, SEXP PMatSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat_big(vMat_bigSEXP);
    Rcpp::traits::input_parameter< List >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(HomogeneityValueNested(Hetx, vMat_big, PMat, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// NormalizedEntropy
NumericVector NormalizedEntropy(NumericMatrix Hetx, List PMat, int nrp, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_NormalizedEntropy(SEXP HetxSEXP, SEXP PMatSEXP, SEXP nrpSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< List >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< int >::type nrp(nrpSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(NormalizedEntropy(Hetx, PMat, nrp, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// NormalizedEntropyNested
NumericVector NormalizedEntropyNested(NumericMatrix Hetx, NumericMatrix vMat_big, List PMat, int nrp, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_NormalizedEntropyNested(SEXP HetxSEXP, SEXP vMat_bigSEXP, SEXP PMatSEXP, SEXP nrpSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat_big(vMat_bigSEXP);
    Rcpp::traits::input_parameter< List >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< int >::type nrp(nrpSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(NormalizedEntropyNested(Hetx, vMat_big, PMat, nrp, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// ProbabilityMatrixHorizontalDynamic
List ProbabilityMatrixHorizontalDynamic(NumericMatrix vMat, int d, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_ProbabilityMatrixHorizontalDynamic(SEXP vMatSEXP, SEXP dSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat(vMatSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(ProbabilityMatrixHorizontalDynamic(vMat, d, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// ProbabilityMatrixHorizontalNested
List ProbabilityMatrixHorizontalNested(NumericMatrix vMat, NumericMatrix vMat_big, int d, bool display_progress);
RcppExport SEXP _StrucDiv2_ProbabilityMatrixHorizontalNested(SEXP vMatSEXP, SEXP vMat_bigSEXP, SEXP dSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat(vMatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat_big(vMat_bigSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(ProbabilityMatrixHorizontalNested(vMat, vMat_big, d, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// ProbabilityMatrixHorizontalPost
List ProbabilityMatrixHorizontalPost(NumericMatrix vMat, NumericMatrix x, int d, int nrp, int nrp_big, bool display_progress);
RcppExport SEXP _StrucDiv2_ProbabilityMatrixHorizontalPost(SEXP vMatSEXP, SEXP xSEXP, SEXP dSEXP, SEXP nrpSEXP, SEXP nrp_bigSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat(vMatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type nrp(nrpSEXP);
    Rcpp::traits::input_parameter< int >::type nrp_big(nrp_bigSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(ProbabilityMatrixHorizontalPost(vMat, x, d, nrp, nrp_big, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// ProbabilityMatrixHorizontalPrior
NumericMatrix ProbabilityMatrixHorizontalPrior(NumericMatrix vMat, int d, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_ProbabilityMatrixHorizontalPrior(SEXP vMatSEXP, SEXP dSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat(vMatSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(ProbabilityMatrixHorizontalPrior(vMat, d, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// ProbabilityMatrixDiagonal135Dynamic
List ProbabilityMatrixDiagonal135Dynamic(NumericMatrix vMat, int d, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_ProbabilityMatrixDiagonal135Dynamic(SEXP vMatSEXP, SEXP dSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat(vMatSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(ProbabilityMatrixDiagonal135Dynamic(vMat, d, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// ProbabilityMatrixDiagonal135Nested
List ProbabilityMatrixDiagonal135Nested(NumericMatrix vMat, NumericMatrix vMat_big, int d, bool display_progress);
RcppExport SEXP _StrucDiv2_ProbabilityMatrixDiagonal135Nested(SEXP vMatSEXP, SEXP vMat_bigSEXP, SEXP dSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat(vMatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat_big(vMat_bigSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(ProbabilityMatrixDiagonal135Nested(vMat, vMat_big, d, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// ProbabilityMatrixDiagonal135Post
List ProbabilityMatrixDiagonal135Post(NumericMatrix vMat, NumericMatrix x, int d, int nrp, int nrp_big, bool display_progress);
RcppExport SEXP _StrucDiv2_ProbabilityMatrixDiagonal135Post(SEXP vMatSEXP, SEXP xSEXP, SEXP dSEXP, SEXP nrpSEXP, SEXP nrp_bigSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat(vMatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type nrp(nrpSEXP);
    Rcpp::traits::input_parameter< int >::type nrp_big(nrp_bigSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(ProbabilityMatrixDiagonal135Post(vMat, x, d, nrp, nrp_big, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// ProbabilityMatrixDiagonal135Prior
NumericMatrix ProbabilityMatrixDiagonal135Prior(NumericMatrix vMat, int d, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_ProbabilityMatrixDiagonal135Prior(SEXP vMatSEXP, SEXP dSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat(vMatSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(ProbabilityMatrixDiagonal135Prior(vMat, d, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// ProbabilityMatrixDiagonal45
NumericMatrix ProbabilityMatrixDiagonal45(NumericMatrix xMat, int d, NumericVector Values);
RcppExport SEXP _StrucDiv2_ProbabilityMatrixDiagonal45(SEXP xMatSEXP, SEXP dSEXP, SEXP ValuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xMat(xMatSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Values(ValuesSEXP);
    rcpp_result_gen = Rcpp::wrap(ProbabilityMatrixDiagonal45(xMat, d, Values));
    return rcpp_result_gen;
END_RCPP
}
// ProbabilityMatrixDiagonal45Dynamic
List ProbabilityMatrixDiagonal45Dynamic(NumericMatrix vMat, int d, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_ProbabilityMatrixDiagonal45Dynamic(SEXP vMatSEXP, SEXP dSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat(vMatSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(ProbabilityMatrixDiagonal45Dynamic(vMat, d, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// ProbabilityMatrixDiagonal45Nested
List ProbabilityMatrixDiagonal45Nested(NumericMatrix vMat, NumericMatrix vMat_big, int d, bool display_progress);
RcppExport SEXP _StrucDiv2_ProbabilityMatrixDiagonal45Nested(SEXP vMatSEXP, SEXP vMat_bigSEXP, SEXP dSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat(vMatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat_big(vMat_bigSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(ProbabilityMatrixDiagonal45Nested(vMat, vMat_big, d, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// ProbabilityMatrixDiagonal45Post
List ProbabilityMatrixDiagonal45Post(NumericMatrix vMat, NumericMatrix x, int d, int nrp, int nrp_big, bool display_progress);
RcppExport SEXP _StrucDiv2_ProbabilityMatrixDiagonal45Post(SEXP vMatSEXP, SEXP xSEXP, SEXP dSEXP, SEXP nrpSEXP, SEXP nrp_bigSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat(vMatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type nrp(nrpSEXP);
    Rcpp::traits::input_parameter< int >::type nrp_big(nrp_bigSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(ProbabilityMatrixDiagonal45Post(vMat, x, d, nrp, nrp_big, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// ProbabilityMatrixDiagonal45Prior
NumericMatrix ProbabilityMatrixDiagonal45Prior(NumericMatrix vMat, int d, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_ProbabilityMatrixDiagonal45Prior(SEXP vMatSEXP, SEXP dSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat(vMatSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(ProbabilityMatrixDiagonal45Prior(vMat, d, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// ProbabilityMatrixVerticalDynamic
List ProbabilityMatrixVerticalDynamic(NumericMatrix vMat, int d, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_ProbabilityMatrixVerticalDynamic(SEXP vMatSEXP, SEXP dSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat(vMatSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(ProbabilityMatrixVerticalDynamic(vMat, d, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// ProbabilityMatrixVerticalNested
List ProbabilityMatrixVerticalNested(NumericMatrix vMat, NumericMatrix vMat_big, int d, bool display_progress);
RcppExport SEXP _StrucDiv2_ProbabilityMatrixVerticalNested(SEXP vMatSEXP, SEXP vMat_bigSEXP, SEXP dSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat(vMatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat_big(vMat_bigSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(ProbabilityMatrixVerticalNested(vMat, vMat_big, d, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// ProbabilityMatrixVerticalPost
List ProbabilityMatrixVerticalPost(NumericMatrix vMat, NumericMatrix x, int d, int nrp, int nrp_big, bool display_progress);
RcppExport SEXP _StrucDiv2_ProbabilityMatrixVerticalPost(SEXP vMatSEXP, SEXP xSEXP, SEXP dSEXP, SEXP nrpSEXP, SEXP nrp_bigSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat(vMatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type nrp(nrpSEXP);
    Rcpp::traits::input_parameter< int >::type nrp_big(nrp_bigSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(ProbabilityMatrixVerticalPost(vMat, x, d, nrp, nrp_big, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// ProbabilityMatrixVerticalPrior
NumericMatrix ProbabilityMatrixVerticalPrior(NumericMatrix vMat, int d, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_ProbabilityMatrixVerticalPrior(SEXP vMatSEXP, SEXP dSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat(vMatSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(ProbabilityMatrixVerticalPrior(vMat, d, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// ProbabilityMatrixAllDynamic
List ProbabilityMatrixAllDynamic(NumericMatrix vMat, int d, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_ProbabilityMatrixAllDynamic(SEXP vMatSEXP, SEXP dSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat(vMatSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(ProbabilityMatrixAllDynamic(vMat, d, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// ProbabilityMatrixAllNested
List ProbabilityMatrixAllNested(NumericMatrix vMat, NumericMatrix vMat_big, int d, bool display_progress);
RcppExport SEXP _StrucDiv2_ProbabilityMatrixAllNested(SEXP vMatSEXP, SEXP vMat_bigSEXP, SEXP dSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat(vMatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat_big(vMat_bigSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(ProbabilityMatrixAllNested(vMat, vMat_big, d, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// ProbabilityMatrixAllNestedParallel
NumericMatrix ProbabilityMatrixAllNestedParallel(NumericVector vMat, NumericVector vMat_big, int d, bool display_progress);
RcppExport SEXP _StrucDiv2_ProbabilityMatrixAllNestedParallel(SEXP vMatSEXP, SEXP vMat_bigSEXP, SEXP dSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vMat(vMatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vMat_big(vMat_bigSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(ProbabilityMatrixAllNestedParallel(vMat, vMat_big, d, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// ProbabilityMatrixAllPost
List ProbabilityMatrixAllPost(NumericMatrix vMat, NumericMatrix x, int d, int nrp, int nrp_big, bool display_progress);
RcppExport SEXP _StrucDiv2_ProbabilityMatrixAllPost(SEXP vMatSEXP, SEXP xSEXP, SEXP dSEXP, SEXP nrpSEXP, SEXP nrp_bigSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat(vMatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type nrp(nrpSEXP);
    Rcpp::traits::input_parameter< int >::type nrp_big(nrp_bigSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(ProbabilityMatrixAllPost(vMat, x, d, nrp, nrp_big, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// ProbabilityMatrixAllPrior
NumericMatrix ProbabilityMatrixAllPrior(NumericMatrix vMat, int d, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_ProbabilityMatrixAllPrior(SEXP vMatSEXP, SEXP dSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat(vMatSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(ProbabilityMatrixAllPrior(vMat, d, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// WeightedEntropyAbsRank
NumericVector WeightedEntropyAbsRank(NumericMatrix Hetx, List PMat, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_WeightedEntropyAbsRank(SEXP HetxSEXP, SEXP PMatSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< List >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(WeightedEntropyAbsRank(Hetx, PMat, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// WeightedEntropyAbsRankNested
NumericVector WeightedEntropyAbsRankNested(NumericMatrix Hetx, NumericMatrix vMat_big, List PMat, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_WeightedEntropyAbsRankNested(SEXP HetxSEXP, SEXP vMat_bigSEXP, SEXP PMatSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat_big(vMat_bigSEXP);
    Rcpp::traits::input_parameter< List >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(WeightedEntropyAbsRankNested(Hetx, vMat_big, PMat, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// WeightedEntropyAbsValue
NumericVector WeightedEntropyAbsValue(NumericMatrix Hetx, List PMat, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_WeightedEntropyAbsValue(SEXP HetxSEXP, SEXP PMatSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< List >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(WeightedEntropyAbsValue(Hetx, PMat, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// WeightedEntropyAbsValueNested
NumericVector WeightedEntropyAbsValueNested(NumericMatrix Hetx, NumericMatrix vMat_big, List PMat, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_WeightedEntropyAbsValueNested(SEXP HetxSEXP, SEXP vMat_bigSEXP, SEXP PMatSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat_big(vMat_bigSEXP);
    Rcpp::traits::input_parameter< List >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(WeightedEntropyAbsValueNested(Hetx, vMat_big, PMat, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// WeightedEntropyAbsValueParallel
double WeightedEntropyAbsValueParallel(NumericVector Hetx, NumericMatrix PMat, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_WeightedEntropyAbsValueParallel(SEXP HetxSEXP, SEXP PMatSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(WeightedEntropyAbsValueParallel(Hetx, PMat, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// WeightedEntropySqrRank
NumericVector WeightedEntropySqrRank(NumericMatrix Hetx, List PMat, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_WeightedEntropySqrRank(SEXP HetxSEXP, SEXP PMatSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< List >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(WeightedEntropySqrRank(Hetx, PMat, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// WeightedEntropySqrRankNested
NumericVector WeightedEntropySqrRankNested(NumericMatrix Hetx, NumericMatrix vMat_big, List PMat, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_WeightedEntropySqrRankNested(SEXP HetxSEXP, SEXP vMat_bigSEXP, SEXP PMatSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat_big(vMat_bigSEXP);
    Rcpp::traits::input_parameter< List >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(WeightedEntropySqrRankNested(Hetx, vMat_big, PMat, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// WeightedEntropySqrValue
NumericVector WeightedEntropySqrValue(NumericMatrix Hetx, List PMat, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_WeightedEntropySqrValue(SEXP HetxSEXP, SEXP PMatSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< List >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(WeightedEntropySqrValue(Hetx, PMat, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// WeightedEntropySqrValueNested
NumericVector WeightedEntropySqrValueNested(NumericMatrix Hetx, NumericMatrix vMat_big, List PMat, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_WeightedEntropySqrValueNested(SEXP HetxSEXP, SEXP vMat_bigSEXP, SEXP PMatSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type vMat_big(vMat_bigSEXP);
    Rcpp::traits::input_parameter< List >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(WeightedEntropySqrValueNested(Hetx, vMat_big, PMat, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// WeightedEntropySqrValueParallel
NumericVector WeightedEntropySqrValueParallel(NumericVector Hetx, NumericMatrix PMat, bool narm, bool display_progress);
RcppExport SEXP _StrucDiv2_WeightedEntropySqrValueParallel(SEXP HetxSEXP, SEXP PMatSEXP, SEXP narmSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Hetx(HetxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type PMat(PMatSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(WeightedEntropySqrValueParallel(Hetx, PMat, narm, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// do_focal_get
NumericVector do_focal_get(NumericMatrix d, NumericVector dim, NumericVector ngb);
RcppExport SEXP _StrucDiv2_do_focal_get(SEXP dSEXP, SEXP dimSEXP, SEXP ngbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type d(dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ngb(ngbSEXP);
    rcpp_result_gen = Rcpp::wrap(do_focal_get(d, dim, ngb));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_StrucDiv2_ContrastRank", (DL_FUNC) &_StrucDiv2_ContrastRank, 4},
    {"_StrucDiv2_ContrastRankNested", (DL_FUNC) &_StrucDiv2_ContrastRankNested, 5},
    {"_StrucDiv2_ContrastValue", (DL_FUNC) &_StrucDiv2_ContrastValue, 4},
    {"_StrucDiv2_ContrastValueNested", (DL_FUNC) &_StrucDiv2_ContrastValueNested, 5},
    {"_StrucDiv2_DissimilarityRank", (DL_FUNC) &_StrucDiv2_DissimilarityRank, 4},
    {"_StrucDiv2_DissimilarityRankNested", (DL_FUNC) &_StrucDiv2_DissimilarityRankNested, 5},
    {"_StrucDiv2_DissimilarityValue", (DL_FUNC) &_StrucDiv2_DissimilarityValue, 4},
    {"_StrucDiv2_DissimilarityValueNested", (DL_FUNC) &_StrucDiv2_DissimilarityValueNested, 5},
    {"_StrucDiv2_Entropy", (DL_FUNC) &_StrucDiv2_Entropy, 4},
    {"_StrucDiv2_EntropyNested", (DL_FUNC) &_StrucDiv2_EntropyNested, 5},
    {"_StrucDiv2_EntropyParallel", (DL_FUNC) &_StrucDiv2_EntropyParallel, 4},
    {"_StrucDiv2_HomogeneityRank", (DL_FUNC) &_StrucDiv2_HomogeneityRank, 4},
    {"_StrucDiv2_HomogeneityRankNested", (DL_FUNC) &_StrucDiv2_HomogeneityRankNested, 5},
    {"_StrucDiv2_HomogeneityValue", (DL_FUNC) &_StrucDiv2_HomogeneityValue, 4},
    {"_StrucDiv2_HomogeneityValueNested", (DL_FUNC) &_StrucDiv2_HomogeneityValueNested, 5},
    {"_StrucDiv2_NormalizedEntropy", (DL_FUNC) &_StrucDiv2_NormalizedEntropy, 5},
    {"_StrucDiv2_NormalizedEntropyNested", (DL_FUNC) &_StrucDiv2_NormalizedEntropyNested, 6},
    {"_StrucDiv2_ProbabilityMatrixHorizontalDynamic", (DL_FUNC) &_StrucDiv2_ProbabilityMatrixHorizontalDynamic, 4},
    {"_StrucDiv2_ProbabilityMatrixHorizontalNested", (DL_FUNC) &_StrucDiv2_ProbabilityMatrixHorizontalNested, 4},
    {"_StrucDiv2_ProbabilityMatrixHorizontalPost", (DL_FUNC) &_StrucDiv2_ProbabilityMatrixHorizontalPost, 6},
    {"_StrucDiv2_ProbabilityMatrixHorizontalPrior", (DL_FUNC) &_StrucDiv2_ProbabilityMatrixHorizontalPrior, 4},
    {"_StrucDiv2_ProbabilityMatrixDiagonal135Dynamic", (DL_FUNC) &_StrucDiv2_ProbabilityMatrixDiagonal135Dynamic, 4},
    {"_StrucDiv2_ProbabilityMatrixDiagonal135Nested", (DL_FUNC) &_StrucDiv2_ProbabilityMatrixDiagonal135Nested, 4},
    {"_StrucDiv2_ProbabilityMatrixDiagonal135Post", (DL_FUNC) &_StrucDiv2_ProbabilityMatrixDiagonal135Post, 6},
    {"_StrucDiv2_ProbabilityMatrixDiagonal135Prior", (DL_FUNC) &_StrucDiv2_ProbabilityMatrixDiagonal135Prior, 4},
    {"_StrucDiv2_ProbabilityMatrixDiagonal45", (DL_FUNC) &_StrucDiv2_ProbabilityMatrixDiagonal45, 3},
    {"_StrucDiv2_ProbabilityMatrixDiagonal45Dynamic", (DL_FUNC) &_StrucDiv2_ProbabilityMatrixDiagonal45Dynamic, 4},
    {"_StrucDiv2_ProbabilityMatrixDiagonal45Nested", (DL_FUNC) &_StrucDiv2_ProbabilityMatrixDiagonal45Nested, 4},
    {"_StrucDiv2_ProbabilityMatrixDiagonal45Post", (DL_FUNC) &_StrucDiv2_ProbabilityMatrixDiagonal45Post, 6},
    {"_StrucDiv2_ProbabilityMatrixDiagonal45Prior", (DL_FUNC) &_StrucDiv2_ProbabilityMatrixDiagonal45Prior, 4},
    {"_StrucDiv2_ProbabilityMatrixVerticalDynamic", (DL_FUNC) &_StrucDiv2_ProbabilityMatrixVerticalDynamic, 4},
    {"_StrucDiv2_ProbabilityMatrixVerticalNested", (DL_FUNC) &_StrucDiv2_ProbabilityMatrixVerticalNested, 4},
    {"_StrucDiv2_ProbabilityMatrixVerticalPost", (DL_FUNC) &_StrucDiv2_ProbabilityMatrixVerticalPost, 6},
    {"_StrucDiv2_ProbabilityMatrixVerticalPrior", (DL_FUNC) &_StrucDiv2_ProbabilityMatrixVerticalPrior, 4},
    {"_StrucDiv2_ProbabilityMatrixAllDynamic", (DL_FUNC) &_StrucDiv2_ProbabilityMatrixAllDynamic, 4},
    {"_StrucDiv2_ProbabilityMatrixAllNested", (DL_FUNC) &_StrucDiv2_ProbabilityMatrixAllNested, 4},
    {"_StrucDiv2_ProbabilityMatrixAllNestedParallel", (DL_FUNC) &_StrucDiv2_ProbabilityMatrixAllNestedParallel, 4},
    {"_StrucDiv2_ProbabilityMatrixAllPost", (DL_FUNC) &_StrucDiv2_ProbabilityMatrixAllPost, 6},
    {"_StrucDiv2_ProbabilityMatrixAllPrior", (DL_FUNC) &_StrucDiv2_ProbabilityMatrixAllPrior, 4},
    {"_StrucDiv2_WeightedEntropyAbsRank", (DL_FUNC) &_StrucDiv2_WeightedEntropyAbsRank, 4},
    {"_StrucDiv2_WeightedEntropyAbsRankNested", (DL_FUNC) &_StrucDiv2_WeightedEntropyAbsRankNested, 5},
    {"_StrucDiv2_WeightedEntropyAbsValue", (DL_FUNC) &_StrucDiv2_WeightedEntropyAbsValue, 4},
    {"_StrucDiv2_WeightedEntropyAbsValueNested", (DL_FUNC) &_StrucDiv2_WeightedEntropyAbsValueNested, 5},
    {"_StrucDiv2_WeightedEntropyAbsValueParallel", (DL_FUNC) &_StrucDiv2_WeightedEntropyAbsValueParallel, 4},
    {"_StrucDiv2_WeightedEntropySqrRank", (DL_FUNC) &_StrucDiv2_WeightedEntropySqrRank, 4},
    {"_StrucDiv2_WeightedEntropySqrRankNested", (DL_FUNC) &_StrucDiv2_WeightedEntropySqrRankNested, 5},
    {"_StrucDiv2_WeightedEntropySqrValue", (DL_FUNC) &_StrucDiv2_WeightedEntropySqrValue, 4},
    {"_StrucDiv2_WeightedEntropySqrValueNested", (DL_FUNC) &_StrucDiv2_WeightedEntropySqrValueNested, 5},
    {"_StrucDiv2_WeightedEntropySqrValueParallel", (DL_FUNC) &_StrucDiv2_WeightedEntropySqrValueParallel, 4},
    {"_StrucDiv2_do_focal_get", (DL_FUNC) &_StrucDiv2_do_focal_get, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_StrucDiv2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
