# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.ContrastRank <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_ContrastRank`, Hetx, PMat, narm, display_progress)
}

.ContrastRankNested <- function(Hetx, vMat_big, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_ContrastRankNested`, Hetx, vMat_big, PMat, narm, display_progress)
}

.ContrastRankRef <- function(PMat) {
    .Call(`_StrucDiv_ContrastRankRef`, PMat)
}

.ContrastValue <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_ContrastValue`, Hetx, PMat, narm, display_progress)
}

.ContrastValueNested <- function(Hetx, vMat_big, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_ContrastValueNested`, Hetx, vMat_big, PMat, narm, display_progress)
}

.ContrastValueRef <- function(PMat, xVal) {
    .Call(`_StrucDiv_ContrastValueRef`, PMat, xVal)
}

.DissimilarityRank <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_DissimilarityRank`, Hetx, PMat, narm, display_progress)
}

.DissimilarityRankNested <- function(Hetx, vMat_big, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_DissimilarityRankNested`, Hetx, vMat_big, PMat, narm, display_progress)
}

.DissimilarityRankRef <- function(PMat) {
    .Call(`_StrucDiv_DissimilarityRankRef`, PMat)
}

.DissimilarityValue <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_DissimilarityValue`, Hetx, PMat, narm, display_progress)
}

.DissimilarityValueNested <- function(Hetx, vMat_big, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_DissimilarityValueNested`, Hetx, vMat_big, PMat, narm, display_progress)
}

.DissimilarityValueRef <- function(PMat, xVal) {
    .Call(`_StrucDiv_DissimilarityValueRef`, PMat, xVal)
}

.Entropy <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_Entropy`, Hetx, PMat, narm, display_progress)
}

.EntropyNested <- function(Hetx, vMat_big, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_EntropyNested`, Hetx, vMat_big, PMat, narm, display_progress)
}

.EntropyRef <- function(PMat, xVal) {
    .Call(`_StrucDiv_EntropyRef`, PMat, xVal)
}

.HomogeneityRank <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_HomogeneityRank`, Hetx, PMat, narm, display_progress)
}

.HomogeneityRankNested <- function(Hetx, vMat_big, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_HomogeneityRankNested`, Hetx, vMat_big, PMat, narm, display_progress)
}

.HomogeneityRankRef <- function(PMat) {
    .Call(`_StrucDiv_HomogeneityRankRef`, PMat)
}

.HomogeneityValue <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_HomogeneityValue`, Hetx, PMat, narm, display_progress)
}

.HomogeneityValueNested <- function(Hetx, vMat_big, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_HomogeneityValueNested`, Hetx, vMat_big, PMat, narm, display_progress)
}

.HomogeneityValueRef <- function(PMat, xVal) {
    .Call(`_StrucDiv_HomogeneityValueRef`, PMat, xVal)
}

.NormalizedEntropy <- function(Hetx, PMat, nrp, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_NormalizedEntropy`, Hetx, PMat, nrp, narm, display_progress)
}

.NormalizedEntropyNested <- function(Hetx, vMat_big, PMat, nrp, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_NormalizedEntropyNested`, Hetx, vMat_big, PMat, nrp, narm, display_progress)
}

.NormalizedEntropyRef <- function(PMat, xVal, nrp) {
    .Call(`_StrucDiv_NormalizedEntropyRef`, PMat, xVal, nrp)
}

.ProbabilityMatrixHorizontal <- function(xMat, d, Values) {
    .Call(`_StrucDiv_ProbabilityMatrixHorizontal`, xMat, d, Values)
}

.ProbabilityMatrixHorizontalDynamic <- function(vMat, d, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_ProbabilityMatrixHorizontalDynamic`, vMat, d, narm, display_progress)
}

.ProbabilityMatrixHorizontalNested <- function(vMat, vMat_big, d, display_progress = TRUE) {
    .Call(`_StrucDiv_ProbabilityMatrixHorizontalNested`, vMat, vMat_big, d, display_progress)
}

.ProbabilityMatrixHorizontalPost <- function(vMat, x, d, nrp, nrp_big, display_progress = TRUE) {
    .Call(`_StrucDiv_ProbabilityMatrixHorizontalPost`, vMat, x, d, nrp, nrp_big, display_progress)
}

.ProbabilityMatrixDiagonal135 <- function(xMat, d, Values) {
    .Call(`_StrucDiv_ProbabilityMatrixDiagonal135`, xMat, d, Values)
}

.ProbabilityMatrixDiagonal135Dynamic <- function(vMat, d, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_ProbabilityMatrixDiagonal135Dynamic`, vMat, d, narm, display_progress)
}

.ProbabilityMatrixDiagonal135Nested <- function(vMat, vMat_big, d, display_progress = TRUE) {
    .Call(`_StrucDiv_ProbabilityMatrixDiagonal135Nested`, vMat, vMat_big, d, display_progress)
}

.ProbabilityMatrixDiagonal135Post <- function(vMat, x, d, nrp, nrp_big, display_progress = TRUE) {
    .Call(`_StrucDiv_ProbabilityMatrixDiagonal135Post`, vMat, x, d, nrp, nrp_big, display_progress)
}

.ProbabilityMatrixDiagonal45 <- function(xMat, d, Values) {
    .Call(`_StrucDiv_ProbabilityMatrixDiagonal45`, xMat, d, Values)
}

.ProbabilityMatrixDiagonal45Dynamic <- function(vMat, d, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_ProbabilityMatrixDiagonal45Dynamic`, vMat, d, narm, display_progress)
}

.ProbabilityMatrixDiagonal45Nested <- function(vMat, vMat_big, d, display_progress = TRUE) {
    .Call(`_StrucDiv_ProbabilityMatrixDiagonal45Nested`, vMat, vMat_big, d, display_progress)
}

.ProbabilityMatrixDiagonal45Post <- function(vMat, x, d, nrp, nrp_big, display_progress = TRUE) {
    .Call(`_StrucDiv_ProbabilityMatrixDiagonal45Post`, vMat, x, d, nrp, nrp_big, display_progress)
}

.ProbabilityMatrixVertical <- function(xMat, d, Values) {
    .Call(`_StrucDiv_ProbabilityMatrixVertical`, xMat, d, Values)
}

.ProbabilityMatrixVerticalDynamic <- function(vMat, d, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_ProbabilityMatrixVerticalDynamic`, vMat, d, narm, display_progress)
}

.ProbabilityMatrixVerticalNested <- function(vMat, vMat_big, d, display_progress = TRUE) {
    .Call(`_StrucDiv_ProbabilityMatrixVerticalNested`, vMat, vMat_big, d, display_progress)
}

.ProbabilityMatrixVerticalPost <- function(vMat, x, d, nrp, nrp_big, display_progress = TRUE) {
    .Call(`_StrucDiv_ProbabilityMatrixVerticalPost`, vMat, x, d, nrp, nrp_big, display_progress)
}

.ProbabilityMatrixAll <- function(xMat, d, Values) {
    .Call(`_StrucDiv_ProbabilityMatrixAll`, xMat, d, Values)
}

.ProbabilityMatrixAllDynamic <- function(vMat, d, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_ProbabilityMatrixAllDynamic`, vMat, d, narm, display_progress)
}

.ProbabilityMatrixAllNested <- function(vMat, vMat_big, d, display_progress = TRUE) {
    .Call(`_StrucDiv_ProbabilityMatrixAllNested`, vMat, vMat_big, d, display_progress)
}

.ProbabilityMatrixAllPost <- function(vMat, x, d, nrp, nrp_big, display_progress = TRUE) {
    .Call(`_StrucDiv_ProbabilityMatrixAllPost`, vMat, x, d, nrp, nrp_big, display_progress)
}

.WeightedEntropyAbsRank <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_WeightedEntropyAbsRank`, Hetx, PMat, narm, display_progress)
}

.WeightedEntropyAbsRankNested <- function(Hetx, vMat_big, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_WeightedEntropyAbsRankNested`, Hetx, vMat_big, PMat, narm, display_progress)
}

.WeightedEntropyAbsRankRef <- function(PMat) {
    .Call(`_StrucDiv_WeightedEntropyAbsRankRef`, PMat)
}

.WeightedEntropyAbsValue <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_WeightedEntropyAbsValue`, Hetx, PMat, narm, display_progress)
}

.WeightedEntropyAbsValueNested <- function(Hetx, vMat_big, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_WeightedEntropyAbsValueNested`, Hetx, vMat_big, PMat, narm, display_progress)
}

.WeightedEntropyAbsValueRef <- function(PMat, xVal) {
    .Call(`_StrucDiv_WeightedEntropyAbsValueRef`, PMat, xVal)
}

.WeightedEntropySqrRank <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_WeightedEntropySqrRank`, Hetx, PMat, narm, display_progress)
}

.WeightedEntropySqrRankNested <- function(Hetx, vMat_big, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_WeightedEntropySqrRankNested`, Hetx, vMat_big, PMat, narm, display_progress)
}

.WeightedEntropySqrRankRef <- function(PMat) {
    .Call(`_StrucDiv_WeightedEntropySqrRankRef`, PMat)
}

.WeightedEntropySqrValue <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_WeightedEntropySqrValue`, Hetx, PMat, narm, display_progress)
}

.WeightedEntropySqrValueNested <- function(Hetx, vMat_big, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_WeightedEntropySqrValueNested`, Hetx, vMat_big, PMat, narm, display_progress)
}

.WeightedEntropySqrValueRef <- function(PMat, xVal) {
    .Call(`_StrucDiv_WeightedEntropySqrValueRef`, PMat, xVal)
}

.focal_get <- function(d, dim, ngb) {
    .Call(`_StrucDiv_do_focal_get`, d, dim, ngb)
}

