# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.ContrastRank <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv2_ContrastRank`, Hetx, PMat, narm, display_progress)
}

.ContrastValue <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv2_ContrastValue`, Hetx, PMat, narm, display_progress)
}

.DissimilarityRank <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv2_DissimilarityRank`, Hetx, PMat, narm, display_progress)
}

.DissimilarityValue <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv2_DissimilarityValue`, Hetx, PMat, narm, display_progress)
}

.Entropy <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv2_Entropy`, Hetx, PMat, narm, display_progress)
}

.HomogeneityRank <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv2_HomogeneityRank`, Hetx, PMat, narm, display_progress)
}

.HomogeneityValue <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv2_HomogeneityValue`, Hetx, PMat, narm, display_progress)
}

.NormalizedEntropy <- function(Hetx, PMat, nrp, narm, display_progress = TRUE) {
    .Call(`_StrucDiv2_NormalizedEntropy`, Hetx, PMat, nrp, narm, display_progress)
}

.ProbabilityMatrixHorizontalDynamic <- function(vMat, d, narm, display_progress = TRUE) {
    .Call(`_StrucDiv2_ProbabilityMatrixHorizontalDynamic`, vMat, d, narm, display_progress)
}

.ProbabilityMatrixHorizontalNested <- function(vMat, vMat_big, d, narm, display_progress = TRUE) {
    .Call(`_StrucDiv2_ProbabilityMatrixHorizontalNested`, vMat, vMat_big, d, narm, display_progress)
}

.ProbabilityMatrixDiagonal135Dynamic <- function(vMat, d, narm, display_progress = TRUE) {
    .Call(`_StrucDiv2_ProbabilityMatrixDiagonal135Dynamic`, vMat, d, narm, display_progress)
}

.ProbabilityMatrixDiagonal135Nested <- function(vMat, vMat_big, d, narm, display_progress = TRUE) {
    .Call(`_StrucDiv2_ProbabilityMatrixDiagonal135Nested`, vMat, vMat_big, d, narm, display_progress)
}

.ProbabilityMatrixDiagonal45Dynamic <- function(vMat, d, narm, display_progress = TRUE) {
    .Call(`_StrucDiv2_ProbabilityMatrixDiagonal45Dynamic`, vMat, d, narm, display_progress)
}

.ProbabilityMatrixDiagonal45Nested <- function(vMat, vMat_big, d, narm, display_progress = TRUE) {
    .Call(`_StrucDiv2_ProbabilityMatrixDiagonal45Nested`, vMat, vMat_big, d, narm, display_progress)
}

.ProbabilityMatrixVerticalDynamic <- function(vMat, d, narm, display_progress = TRUE) {
    .Call(`_StrucDiv2_ProbabilityMatrixVerticalDynamic`, vMat, d, narm, display_progress)
}

.ProbabilityMatrixVerticalNested <- function(vMat, vMat_big, d, narm, display_progress = TRUE) {
    .Call(`_StrucDiv2_ProbabilityMatrixVerticalNested`, vMat, vMat_big, d, narm, display_progress)
}

.ProbabilityMatrixAllDynamic <- function(vMat, d, narm, display_progress = TRUE) {
    .Call(`_StrucDiv2_ProbabilityMatrixAllDynamic`, vMat, d, narm, display_progress)
}

.ProbabilityMatrixAllNested <- function(vMat, vMat_big, d, narm, display_progress = TRUE) {
    .Call(`_StrucDiv2_ProbabilityMatrixAllNested`, vMat, vMat_big, d, narm, display_progress)
}

.WeightedEntropyAbsRank <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv2_WeightedEntropyAbsRank`, Hetx, PMat, narm, display_progress)
}

.WeightedEntropyAbsValue <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv2_WeightedEntropyAbsValue`, Hetx, PMat, narm, display_progress)
}

.WeightedEntropySqrRank <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv2_WeightedEntropySqrRank`, Hetx, PMat, narm, display_progress)
}

.WeightedEntropySqrValue <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv2_WeightedEntropySqrValue`, Hetx, PMat, narm, display_progress)
}

.focal_get <- function(d, dim, ngb) {
    .Call(`_StrucDiv2_do_focal_get`, d, dim, ngb)
}

